### ISSUE TITLE
I meet this error while trying to runserver

### ISSUE THREAD

**Issue by yukepeter** [ciaron/sortable#1]
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form EntryForm needs updating.

**Comment by ciaron** [comment]
This code requires an older version of Django. I've updated it to get past the initial imports in Django >1.8, but there are still errors in running the server (e.g. no URLs available). Probably won't fix them.

See e2538335349f95183033a3dcc4e4dacfffae963b.
